name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm -w -r --filter ./packages/** run build || true

      - name: Typecheck web
        run: pnpm --filter @pocketsomm/web run typecheck || true

      - name: Lint web
        run: pnpm --filter @pocketsomm/web run lint || true

      - name: Build web
        run: pnpm --filter @pocketsomm/web run build
        working-directory: apps/web
