name: Deploy

on:
  push:
    branches: [main] # → dev
    tags: ['v*'] # → prod (e.g. v1.0.0)
  workflow_dispatch:
    inputs:
      stage:
        description: 'Optional SST stage override'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Pick environment based on ref (or manual input)
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'dev' }}

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      SST_STAGE: ${{ inputs.stage != '' && inputs.stage || (startsWith(github.ref, 'refs/tags/v') && 'prod' || 'dev') }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: pocketsomm-deploy

      - name: Deploy (SST)
        run: pnpm sst deploy --stage $SST_STAGE

      - name: Print outputs
        run: pnpm sst print --stage $SST_STAGE
