name: Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      SST_STAGE: pr-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: pocketsomm-preview-clean
      - name: Remove preview stack
        run: pnpm sst remove --stage $SST_STAGE
